### ISSUE TITLE
Proguard rule missing

### ISSUE THREAD

**Issue by tom91136** [tom91136/Akatsuki#12]
Someone emailed me about proguard rules. It's headed for 0.1.0.

**Comment by deanezra** [comment]
After enabling proguard I am seeing the following error at runtime (my fragment is saving its state):

     Caused by: java.lang.RuntimeException: Unable to find generated class for com.<MYAPPPACKAGE>.fragments.t, does the class contain any fields annotated with @Retain(inherited class works too)?

Is there a workaround (while you work on 0.1.0)?

**Comment by tom91136** [comment]
Working on one right now, hold on

**Comment by tom91136** [comment]
Here's a workaround:

    -dontwarn com.sora.util.akatsuki.**
    -keep class com.sora.util.akatsuki.** { *; }
    -keep class **$$BundleRetainer { *; }

I've tested this with the sample app and it works. Do report any further issues as I'm not sure if this covers all use cases. If all goes good, this will be added to the README of  `0.1.0`

**Comment by deanezra** [comment]
Hi Tom,

Thanks! I will try your suggested line tomorrow and reply with whether it 
works.

A more extreme workaround that I found worked was to exclude only my 
fragments classes using proguard (the ones that used akatsuki). But of 
course then I lost the advantages of the proguard in those fragments.

Dean

**Comment by tom91136** [comment]
Actually, I'm not sure whether excluding fragments alone would work. From what I understand, proguard will still go ahead and obfuscate class names of all Akatsuki generated code. 

One possible explanation is that proguard did some static analysis and figured out which classes should be ignored. I'll have to read the docs for proguard again to verify this.

**Comment by deanezra** [comment]
I have been testing my app all of today (with my extreme fragment 
exclusions) and havnt seen the error since. But I must admit proguard is 
alittle bit of a black box for me!

Odd thing is that a separate activity that is using akatsuki isn't excluded 
and I havnt seen the error with proguard enabled on it.

**Comment by deanezra** [comment]
@tom91136 unfortunately I have found that your proguard workaround lines do not work.

Proguard lines tried:

   -dontwarn com.sora.util.akatsuki.**
   -keep class com.sora.util.akatsuki.** { *; }
   -keep class **$$BundleRetainer { *; }

I dont see the error if I do either of the following:
1. disable proguard
or
2. Add the following proguard lines to exclude all my fragments from proguard (not good):
   -keep class com.spottedparrot.android.woofwoof.fragments.* { *; }
   -dontwarn com.spottedparrot.android.woofwoof.fragments.*

   -keep class com.spottedparrot.android.woofwoof.fragments.EditEntryDetailsFragment.* { *; }
   -dontwarn com.spottedparrot.android.woofwoof.fragments.EditEntryDetailsFragment.*

Here's the stacktrace:

E/AndroidRuntime(19057): FATAL EXCEPTION: main
E/AndroidRuntime(19057): Process: com.spottedparrot.android.woofwoof, PID: 19057
E/AndroidRuntime(19057): java.lang.RuntimeException: java.lang.RuntimeException: Unable to find generated class for com.spottedparrot.android.woofwoof.fragments.r, does the class contain any fields annotated with @Retain(inherited class works too)?
E/AndroidRuntime(19057): 	at com.sora.util.akatsuki.Internal.createRetainer(Unknown Source)
E/AndroidRuntime(19057): 	at com.sora.util.akatsuki.Akatsuki.getInstance(Unknown Source)
E/AndroidRuntime(19057): 	at com.sora.util.akatsuki.Akatsuki.save(Unknown Source)
E/AndroidRuntime(19057): 	at com.spottedparrot.android.woofwoof.fragments.r.onSaveInstanceState(Unknown Source)
E/AndroidRuntime(19057): 	at android.support.v4.app.Fragment.performSaveInstanceState(Unknown Source)
E/AndroidRuntime(19057): 	at android.support.v4.app.ar.f(Unknown Source)
E/AndroidRuntime(19057): 	at android.support.v4.app.ar.l(Unknown Source)
E/AndroidRuntime(19057): 	at android.support.v4.app.an.d(Unknown Source)
E/AndroidRuntime(19057): 	at android.support.v4.app.ai.onSaveInstanceState(Unknown Source)
E/AndroidRuntime(19057): 	at com.spottedparrot.android.woofwoof.MainActivity.onSaveInstanceState(Unknown Source)
E/AndroidRuntime(19057): 	at android.app.Activity.performSaveInstanceState(Activity.java:1298)
E/AndroidRuntime(19057): 	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1288)
E/AndroidRuntime(19057): 	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:3989)
E/AndroidRuntime(19057): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3400)
E/AndroidRuntime(19057): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3456)
E/AndroidRuntime(19057): 	at android.app.ActivityThread.access$1200(ActivityThread.java:154)
E/AndroidRuntime(19057): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
E/AndroidRuntime(19057): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19057): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19057): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime(19057): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19057): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19057): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(19057): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(19057): Caused by: java.lang.RuntimeException: Unable to find generated class for com.spottedparrot.android.woofwoof.fragments.r, does the class contain any fields annotated with @Retain(inherited class works too)?

**Comment by tom91136** [comment]
I've figured this out. Yes, you need to keep your fragments. 
I suppose something like this would work:

    -keepclasseswithmembernames class * {
        @com.sora.util.akatsuki.* <fields>;
    }

This adds to the previously mentioned rules, not replacing it
Butterknife does similar things otherwise we can't determine the correct class name

If possible, can you also post your build script? I'm curious what the `buildTypes` section looks like

**Comment by deanezra** [comment]
Hi @tom91136,

Sorry for delay in replying..

So I tried your extra line in combination with your original two and it works!

I have not needed to directly keep the fragment clases. 

So in summary these are the only Akatsuki proguard related rules:


```
# Recommended fix from Akatsuki author tom:
# Working:
-dontwarn com.sora.util.akatsuki.**
-keep class com.sora.util.akatsuki.** { *; }
-keep class **$$BundleRetainer { *; }
-keepclasseswithmembernames class * {
    @com.sora.util.akatsuki.* <fields>;
}
```

**Comment by tom91136** [comment]
Thanks for testing, this will be added to the 0.1.0 release. I'll leave this issue open before then.

**Comment by tom91136** [comment]
0.1.0 is up, closing for now
